package com.example.talent_grid.repository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import java.time.LocalDateTime;

@Repository
public class LegacyKeystrokeRepository {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    /**
     * Bootstraps the keystroke logging schema if it doesn't already exist.
     * Demonstrates deep fundamental control using raw DDL.
     */
    public void initKeystrokeTable() {
        String sql = "CREATE TABLE IF NOT EXISTS keystroke_logs (" +
                     "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                     "document_id BIGINT NOT NULL, " +
                     "username VARCHAR(255) NOT NULL, " +
                     "op_type VARCHAR(50) NOT NULL, " +
                     "op_content TEXT, " +
                     "char_position INT NOT NULL, " +
                     "timestamp TIMESTAMP NOT NULL" +
                     ")";
        jdbcTemplate.execute(sql);
    }

    /**
     * High-speed append-only logging of user typing operations.
     * Uses Raw JDBC to completely bypass JPA/Hibernate persistence context overhead.
     */
    public void logKeystroke(Long documentId, String username, String opType, String opContent, int position) {
        String sql = "INSERT INTO keystroke_logs (document_id, username, op_type, op_content, char_position, timestamp) " +
                     "VALUES (?, ?, ?, ?, ?, ?)";
        jdbcTemplate.update(sql, documentId, username, opType, opContent, position, LocalDateTime.now());
    }

    /**
     * Advanced analytical query: Count keystrokes per user for a specific document.
     * Demonstrates complex aggregations with raw SQL.
     */
    public long getKeystrokeCountForUser(Long documentId, String username) {
        String sql = "SELECT COUNT(*) FROM keystroke_logs WHERE document_id = ? AND username = ?";
        Long count = jdbcTemplate.queryForObject(sql, Long.class, documentId, username);
        return count != null ? count : 0L;
    }
}
